[versions]
kotlin = "2.3.10"
mod-publish = "1.1.+"
fabric-loader = "0.18.0"
fabric-language-kotlin = "1.13.9+kotlin."
konfig = "3.0.1"
modstitch = "0.8.4"

[libraries]
konfig = { module = "dev.nyon:konfig", version.ref = "konfig" }

[plugins]
modstitch = { id = "dev.isxander.modstitch.base", version.ref = "modstitch" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }