name: sync-readme

on:
  push:
    paths:
      - "README.md"
      - "media"
    branches:
      - main
  workflow_dispatch:

jobs:
  modrinth-description:
    runs-on: ubuntu-latest
    name: Sync Modrinth description
    steps:
      - uses: actions/checkout@v7
      - uses: btwonion/mc-readme-sync@v1
        with:
          modrinth-api-key: ${{ secrets.MODRINTH_API_KEY }}
          curseforge-api-key: ${{ secrets.CURSEFORGE_API_KEY }}
          modrinth-project-id: "lg17V3i3"
          curseforge-project-id: "1244691"
          readme-path: README.md